### ISSUE TITLE
Cannot read properties of null (reading 'replace')

### ISSUE THREAD

**Issue by vimtor** [47ng/next-usequerystate#310]
I've tried the provided example and the following error occurs:
- Next.js: 12.3.1
- React.js: 17.0.2

```
project:dev: error - TypeError: Cannot read properties of null (reading 'replace')
project:dev:     at /Users/vimtor/Developer/project/node_modules/next-usequerystate/dist/cjs/useQueryState.js:67:96
project:dev:     at Object.useMemo (/Users/vimtor/Developer/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:1582:19)
project:dev:     at Object.useMemo (/Users/vimtor/Developer/project/node_modules/react/cjs/react.development.js:1532:21)
project:dev:     at useQueryState (/Users/vimtor/Developer/project/node_modules/next-usequerystate/dist/cjs/useQueryState.js:67:39)
project:dev:     at HomePage (webpack-internal:///./pages/index.tsx:223:97)
project:dev:     at processChild (/Users/vimtor/Developer/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
project:dev:     at resolve (/Users/vimtor/Developer/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
project:dev:     at ReactDOMServerRenderer.render (/Users/vimtor/Developer/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
project:dev:     at ReactDOMServerRenderer.read (/Users/vimtor/Developer/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
project:dev:     at Object.renderToString (/Users/vimtor/Developer/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27) {
project:dev:   page: '/'
project:dev: }
```

**Comment by vimtor** [comment]
Okey I just found out that I cannot use the package when using `getServerSideProps` thank you
